version: '3.1'

services:
  service-read:
    image: service-read
    ports:
      - '8501:8501'
    environment:
      - server.port=8501
      - eureka.client.serviceUrl.defaultZone=http://<<eureka-ip>>:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - eureka.instance.ip-address=<<service-read ip>>
      - eureka.instance.non-secure-port=8501
      - eureka.instance.health-check-url-path=/actuator/info
      - management.endpoints.web.exposure.include=health,info
      - management.endpoint.health.show-details=always
